"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$docker_context\
$conda\
$pixi\
$time\
$line_break$character"""

palette = 'catppuccin_macchiato'

# Palette definitions

# Palette definitions
[palettes.catppuccin_macchiato]
color_bg1 = '#fcf4d0'
color_fg0 = '#34374a'
color_bg3 = '#464a5f'
color_rosewater = "#f2c4b8"
color_flamingo = "#f1b8b8"
color_pink = "#f5b6eb"
color_mauve = "#c979ff"
color_bright_red = "#ba0230ff"
color_red = "#f24f79"
color_maroon = "#ff8593"
color_peach = "#ffa44b"
color_yellow = "#f4ce5d"
color_green = "#80d06b"
color_teal = "#57d2d9"
color_sky = "#44e5ff"
color_sapphire = "#60dff5"
color_blue = "#5ea6ff"
color_blue_light = "#7eb8ff"
color_lavender = "#7287fd"
color_lavender_light = "#a1aefbff"
color_text = "#4c4f69"
color_subtext1 = "#5c5f77"
color_subtext0 = "#6c6f85"
color_overlay2 = "#7c7f93"
color_overlay1 = "#8c8fa1"
color_overlay0 = "#9ca0b0"
color_surface2 = "#acb0be"
color_surface1 = "#bcc0cc"
color_surface0 = "#ccd0da"
color_base = "#eff1f5"
color_mantle = "#e6e9ef"
color_crust = "#dce0e8"

[character]
success_symbol = '[\$](bold fg:color_green)'
error_symbol = '[\$](bold fg:color_red)'

[os]
disabled = true
style = "bg:color_red fg:color_fg0"

[username]
show_always = true
style_user = "bg:color_red fg:color_fg0"
style_root = "bg:color_bright_red fg:color_fg0"
format = '[$user@]($style)'

[hostname]
disabled = false
ssh_symbol = '🌐'
ssh_only = false # always show hostname
style = "bg:color_red fg:color_fg0"
format = '[$ssh_symbol$hostname:]($style)'
#format = '[$ssh_symbol$hostname:]($style)'
#format = '[hostname ]($style)'

[directory]
style = "fg:color_fg0 bg:color_peach"
format = "[ $path ]($style)"
truncation_length = 0
truncate_to_repo = false
truncation_symbol = "…/"
repo_root_style = "bold fg:color_fg0 bg:color_yellow"
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '

[git_branch]
#symbol = ""
style = "bg:color_green"
format = '[ [$branch](fg:color_fg0 bg:color_green)]($style)'

[git_status]
style = "bg:color_green"
format = '[[ ($all_status$ahead_behind) ](fg:color_fg0 bg:color_green)]($style) '

[time]
disabled = false
time_format = "%R"
style = "bg:color_blue_light"
format = '[[ @ $time CST ](fg:color_fg0 bg:color_blue_light)]($style)'

[battery]
full_symbol = "• "
charging_symbol = "⇡ "
discharging_symbol = "⇣ "
unknown_symbol = "❓ "
empty_symbol = "❗ "

[erlang]
symbol = "ⓔ "

[nodejs]
symbol = "[⬢](bold green) "

[pulumi]
symbol = "🧊 "

[typst]
symbol = "t "
